version: '3.8'
services:
  postgres:
    image: postgres:latest
    hostname: postgreshost
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}           # Database name
      POSTGRES_USER: ${POSTGRES_USER}       # Corrected variable for username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Password for the user
    ports:
      - "${POSTGRES_PORT}:5432"             # Port mapping for PostgreSQL
    networks:
      - pg_network
    volumes:
      - postgres:/var/lib/postgresql/data   # Fixed syntax

  pgadmin:                                   # Fixed the service name from 'pdadmin' to 'pgadmin'
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_HOST=postgreshost
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - "${PGADMIN_PORT}:80"                  # Port mapping for pgAdmin
    depends_on:
      - postgres

    volumes:
      - ./entrypoint.sh:/entrypoint_custom.sh
    entrypoint: /entrypoint_custom.sh
    user: root
    networks:
      - pg_network          
  
networks:
  pg_network:
    driver: bridge                          
  
volumes:
  postgres: 

