version: '3.1'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}           # Database name
      POSTGRES_USER: ${POSTGRES_USER}       # Corrected variable for username
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Password for the user
    expose:
      - 5432
    ports:
      - "${POSTGRES_PORT}:5432"             # Port mapping for PostgreSQL

  pgadmin:                                   # Fixed the service name from 'pdadmin' to 'pgadmin'
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}      # Email for pgAdmin
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # Password for pgAdmin
    ports:
      - "${PGADMIN_PORT}:80"                  # Port mapping for pgAdmin
    depends_on:
      - postgres
    volumes:
      - "./pgadmin/var/lib/pgadmin:/var/lib/pgadmin"  # Persistent storage for pgAdmin
